server:
  port: 8080

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html;charset=UTF-8
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1483
    url: jdbc:postgresql://localhost:5432/mebook
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

